In [ ]:
#Name: Sahil Shaikh
#Roll No: 54
#Branch: TE AIML
#Practical: Machine Learning Lab
#Experiment No 4

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
import seaborn as sns

In [ ]:
iris=datasets.load_iris()

In [ ]:
x=iris.data
y=iris.target
names=iris.target_names

In [ ]:
names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
x.shape

(150, 4)

In [ ]:
y.shape

(150,)

In [ ]:
df=pd.DataFrame(x, columns=iris.feature_names)
df['species']=iris.target
df['species']=df['species'].replace(to_replace=[0,1,2], value=['setosa', 'versicolor', 'virginica'])

In [ ]:
df.corr()

<ipython-input-11-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20, random_state=1)

In [ ]:
from sklearn.svm import SVC
svm=SVC (kernel='linear', random_state=0)
svm.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
pred=svm.predict(x_test)

In [ ]:
pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2])

In [ ]:
y_test

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2])

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
accuracy_score(y_test,pred)

1.0

In [ ]:
confusion_matrix(y_test,pred)

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]])

In [ ]:
Conclusion:
We have successfully implemented linear SVM on the Iris data set using python.